import { Locale } from 'date-fns';
import { ICurrency, IExposedLanguages } from "../../models/common";
import { Variation } from "../../models/property";
import Stack from "../../models/stack";
export declare class IrBookingEngine {
    token: string;
    propertyId: number;
    baseUrl: string;
    injected: boolean;
    roomtype_id: number;
    redirect_url: string;
    perma_link: string;
    aName: string;
    fromDate: string;
    language: string;
    toDate: string;
    adultCount: string;
    childrenCount: string;
    cur: string;
    aff: string;
    stag: string | null;
    source: {
        code: string;
        desciption: string;
    } | null;
    selectedLocale: Locale;
    currencies: ICurrency[];
    languages: IExposedLanguages[];
    isLoading: boolean;
    private commonService;
    private propertyService;
    private identifier;
    router: Stack<HTMLElement>;
    componentWillLoad(): Promise<void>;
    handleTokenChange(newValue: string, oldValue: string): void;
    modifyLanguage(code: string): void;
    handleCurrencyChange(newValue: string, oldValue: string): void;
    initializeApp(): void;
    initRequest(): Promise<void>;
    checkAffiliate(): import("@/models/property").Affiliate;
    handleVariationChange(e: CustomEvent, variations: Variation[], rateplanId: number, roomTypeId: number): void;
    handleNavigation(e: CustomEvent): void;
    handleResetBooking(e: CustomEvent): Promise<void>;
    resetBooking(resetType?: 'discountOnly' | 'completeReset'): Promise<void>;
    checkAvailability(): Promise<void>;
    renderScreens(): any;
    render(): any;
}
