import { Locale } from 'date-fns';
import { ICurrency, IExposedLanguages } from "../../models/common";
import { IExposedProperty, Variation } from "../../models/property";
import { TSource } from "../../stores/app.store";
import Stack from "../../models/stack";
export declare class IrBookingEngine {
    token: string;
    propertyId: number;
    baseUrl: string;
    injected: boolean;
    roomtype_id: number;
    rateplan_id: number;
    redirect_url: string;
    perma_link: string;
    aName: string;
    fromDate: string;
    language: string;
    toDate: string;
    adultCount: string;
    childrenCount: string;
    cur: string;
    aff: string;
    stag: string | null;
    property: IExposedProperty | null;
    source: TSource | null;
    version: string;
    selectedLocale: Locale;
    currencies: ICurrency[];
    languages: IExposedLanguages[];
    isLoading: boolean;
    router: Stack<HTMLElement>;
    bookingListingScreenOptions: {
        screen: 'bookings' | 'booking-details';
        params: unknown;
    };
    private commonService;
    private propertyService;
    private availabiltyService;
    private identifier;
    componentWillLoad(): Promise<void>;
    handleTokenChange(newValue: string, oldValue: string): void;
    handleSourceChange(newSource: TSource, oldSource: TSource): void;
    handleCurrencyChange(newValue: string, oldValue: string): void;
    setSource(newSource: TSource): void;
    modifyLanguage(code: string): void;
    initializeApp(): void;
    initRequest(): Promise<void>;
    handleVariationChange(e: CustomEvent, variations: Variation[], rateplanId: number, roomTypeId: number): void;
    handleNavigation(e: CustomEvent): void;
    handleResetBooking(e: CustomEvent): Promise<void>;
    handleAuthFinish(e: CustomEvent): void;
    resetBooking(resetType?: 'discountOnly' | 'completeReset'): Promise<void>;
    checkAvailability(): Promise<void>;
    renderScreens(): any;
    disconnectedCallback(): void;
    render(): any;
}
