import { EventEmitter } from '../../../../stencil-public-runtime';
import { TExposedBookingAvailability } from './availability';
export declare class IrAvailibilityHeader {
    fromDate: string;
    toDate: string;
    adultCount: string;
    childrenCount: string;
    exposedBookingAvailabiltyParams: TExposedBookingAvailability;
    target: HTMLElement;
    errorCause: ('date' | 'adult_child')[] | null;
    isLoading: boolean;
    resetBooking: EventEmitter<null>;
    scrollToRoomType: EventEmitter<null>;
    private popoverInstance;
    private toast_timeout;
    private identifier;
    private propertyService;
    private availabiltyService;
    private validator;
    componentWillLoad(): void;
    disableLoading(): void;
    private recheckAvailability;
    handleFromDateChange(newValue: string, oldValue: string): void;
    handleToDateChange(newValue: string, oldValue: string): void;
    handleChildrenCountChange(newValue: string, oldValue: string): void;
    handleAdultCountChange(newValue: string, oldValue: string): void;
    checkAvailability(): Promise<string>;
    handleCheckAvailability(): Promise<void>;
    changeExposedAvailabilityParams(params: Partial<TExposedBookingAvailability>): void;
    handleDateChange(e: CustomEvent): void;
    handleAdultChildChange(e: CustomEvent): void;
    disconnectedCallback(): void;
    shouldRenderErrorToast(): boolean;
    render(): any;
}
