import { Booking } from "../../../models/booking.dto";
export declare class IrBookingListing {
    propertyid: number;
    baseUrl: string;
    language: string;
    headerShown: boolean;
    footerShown: boolean;
    maxPages: number;
    perma_link: string;
    aName: string;
    isLoading: boolean;
    token: string;
    bookings: Booking[];
    currentPage: number;
    total_count: number;
    bookingNumber: any;
    page_mode: 'single' | 'multi';
    activeLink: 'single_booking' | 'all_booking';
    private bookingListingService;
    private commonService;
    private propertyService;
    private bookingListingAppService;
    private booking;
    componentWillLoad(): Promise<void>;
    initializeServices(): void;
    initializeApp(): Promise<void>;
    getBookings(): Promise<any>;
    handleAuthFinish(e: CustomEvent): void;
    getBadgeVariant(code: string): "error" | "success" | "pending";
    handlePageChange(e: CustomEvent<number>): Promise<void>;
    handleLinkChanged(e: CustomEvent): Promise<void>;
    render(): any;
}
