import { EventEmitter } from '../../../stencil-public-runtime';
import { TTabsState } from './nav-types';
import { ICurrency, IExposedLanguages, pages } from "../../../models/commun";
export declare class IrNav {
    currencies: ICurrency[];
    languages: IExposedLanguages[];
    logo: string;
    website: string;
    isBookingListing: boolean;
    showBookingCode: boolean;
    showCurrency: boolean;
    menuShown: boolean;
    routing: EventEmitter<pages>;
    signOut: EventEmitter<null>;
    screenChanged: EventEmitter<pages>;
    currentPage: TTabsState;
    private preferences;
    private dialogRef;
    private sheetRef;
    modalRef: HTMLIrModalElement;
    componentWillLoad(): void;
    handleWebsiteChange(newValue: string, oldValue: string): void;
    handleButtonClick(e: CustomEvent, page: TTabsState): void;
    handleCloseDialog(e: CustomEvent): void;
    renderDialogBody(): any;
    renderLanguageTrigger(): any;
    private handleSignIn;
    handleItemSelect(e: CustomEvent): Promise<CustomEvent<pages>>;
    render(): any;
}
