import { PropertiesByLevel2Response } from "../../services/api/property.service";
import { IExposedProperty } from "../../models/property";
export type CombinedLevel2Properties = {
    cities: string[];
    properties: Map<string, PropertiesByLevel2Response[]>;
};
export declare class IrBookingWidget {
    el: HTMLIrWidgetElement;
    pool: string;
    l: string;
    position: 'fixed' | 'block';
    propertyId: number;
    perma_link: string;
    p: string;
    language: string;
    roomTypeId: string | null;
    aff: string;
    delay: number;
    isPopoverOpen: boolean;
    property: IExposedProperty;
    dateModifiers: any;
    isLoading: boolean;
    isGuestPopoverOpen: boolean;
    dates: {
        from_date: Date | null;
        to_date: Date | null;
    };
    level2Properties: CombinedLevel2Properties;
    selectedCity: string;
    guests: {
        adultCount: number;
        childrenCount: number;
        infants: number;
        childrenAges: string[];
    };
    linkedProperties: IExposedProperty[];
    selectedProperty: IExposedProperty;
    isFetchingProperty: boolean;
    private baseUrl;
    private token;
    private commonService;
    private propertyService;
    private guestPopover;
    private containerRef;
    private elTimout;
    private error;
    private baseGuests;
    private mainWidgetPopupRef;
    componentWillLoad(): void;
    componentDidLoad(): void;
    handleCityChange(newValue: string): void;
    handlePropertyChange(newValue: any, oldValue: any): Promise<void>;
    private hasDisabledDateInRange;
    private get isMultiProperties();
    private get isLevel2Mode();
    private get isSingleProperty();
    private initApp;
    private resetPageFontSize;
    private parseCommaSeparated;
    private initProperty;
    private showWidget;
    private setLevel2Properties;
    private isMultiPropertyMode;
    private handleBooknow;
    private getDateModifiers;
    private validateChildrenAges;
    private renderMultiWidget;
    disconnectedCallback(): void;
    render(): any;
}
