import { EventEmitter } from '../../../../stencil-public-runtime';
import { TExposedBookingAvailability } from './availability';
import { AddAdultsAndChildrenEvent } from '../ir-adult-child-counter/ir-adult-child-counter';
export declare class IrAvailabilityHeader {
    fromDate: string;
    toDate: string;
    adultCount: string;
    childrenCount: string;
    ages: string;
    target: HTMLElement;
    isLoading: boolean;
    exposedBookingAvailabilityParams: TExposedBookingAvailability;
    resetBooking: EventEmitter<null>;
    scrollToRoomType: EventEmitter<null>;
    private errorCause;
    private popoverInstance;
    private toast_timeout;
    private personCounter;
    private propertyService;
    private validator;
    componentWillLoad(): void;
    handleAgesChange(newValue: string, oldValue: string): void;
    handleFromDateChange(newValue: string, oldValue: string): void;
    handleToDateChange(newValue: string, oldValue: string): void;
    handleChildrenCountChange(newValue: string, oldValue: string): void;
    handleAdultCountChange(newValue: string, oldValue: string): void;
    handleDateChange(e: CustomEvent): void;
    handleAdultChildChange(e: CustomEvent<AddAdultsAndChildrenEvent>): void;
    private setDefaultAdultCount;
    private setDefaultChildCount;
    private recheckAvailability;
    private processAges;
    private checkAvailability;
    private handleCheckAvailability;
    private changeExposedAvailabilityParams;
    private shouldRenderErrorToast;
    disconnectedCallback(): void;
    render(): any;
}
