import { z } from 'zod';
export declare const IrUserFormData: z.ZodObject<{
    firstName: z.ZodString;
    lastName: z.ZodString;
    email: z.ZodString;
    mobile_number: z.ZodNumber;
    arrival_time: z.ZodString;
    message: z.ZodOptional<z.ZodString>;
    bookingForSomeoneElse: z.ZodDefault<z.ZodBoolean>;
    country_id: z.ZodNumber;
    country_phone_prefix: z.ZodString;
    id: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
}, "strip", z.ZodTypeAny, {
    firstName?: string;
    lastName?: string;
    email?: string;
    mobile_number?: number;
    arrival_time?: string;
    message?: string;
    bookingForSomeoneElse?: boolean;
    country_id?: number;
    country_phone_prefix?: string;
    id?: number;
}, {
    firstName?: string;
    lastName?: string;
    email?: string;
    mobile_number?: number;
    arrival_time?: string;
    message?: string;
    bookingForSomeoneElse?: boolean;
    country_id?: number;
    country_phone_prefix?: string;
    id?: number;
}>;
export type TUserFormData = z.infer<typeof IrUserFormData>;
export declare const IrGuest: z.ZodObject<{
    address: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    city: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    country_id: z.ZodNumber;
    dob: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    email: z.ZodString;
    first_name: z.ZodString;
    id: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    last_name: z.ZodString;
    mobile: z.ZodNumber;
    subscribe_to_news_letter: z.ZodDefault<z.ZodBoolean>;
    country_phone_prefix: z.ZodString;
    alternative_email: z.ZodNullable<z.ZodOptional<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    address?: string;
    city?: string;
    country_id?: number;
    dob?: string;
    email?: string;
    first_name?: string;
    id?: number;
    last_name?: string;
    mobile?: number;
    subscribe_to_news_letter?: boolean;
    country_phone_prefix?: string;
    alternative_email?: string;
}, {
    address?: string;
    city?: string;
    country_id?: number;
    dob?: string;
    email?: string;
    first_name?: string;
    id?: number;
    last_name?: string;
    mobile?: number;
    subscribe_to_news_letter?: boolean;
    country_phone_prefix?: string;
    alternative_email?: string;
}>;
export type TGuest = z.infer<typeof IrGuest>;
