import { EventEmitter } from '../../../../stencil-public-runtime';
import { Booking } from "../../../../models/booking.dto";
export declare class IrBookingOverview {
    token: string;
    propertyid: number;
    language: string;
    maxPages: number;
    showAllBookings: boolean;
    be: boolean;
    aff: boolean;
    isLoading: boolean;
    bookings: Booking[];
    currentPage: number;
    total_count: number;
    bookingNumber: any;
    page_mode: 'single' | 'multi';
    activeLink: 'single_booking' | 'all_booking';
    selectedBooking: Booking | null;
    selectedMenuIds: Record<string, number>;
    hoveredBooking: any;
    cancelationMessage: string;
    amountToBePayed: number;
    bl_routing: EventEmitter<{
        route: 'booking' | 'booking-details';
        params?: unknown;
    }>;
    private bookingListingService;
    private commonService;
    private propertyService;
    private bookingListingAppService;
    private paymentService;
    private booking;
    private bookingCancelation;
    componentWillLoad(): Promise<void>;
    initializeServices(): void;
    initializeApp(): Promise<void>;
    getBookings(): Promise<any>;
    modifyCancelBooking(booking_nbr: string): void;
    getBadgeVariant(code: string): "error" | "success" | "pending";
    handlePageChange(e: CustomEvent<number>): Promise<void>;
    handleLinkChanged(e: CustomEvent): Promise<void>;
    handleLanguageChanged(e: CustomEvent): Promise<void>;
    fetchCancelationMessage(id: number, roomTypeId: number): Promise<void>;
    private handleBookingCancelation;
    private handleMenuItemChange;
    private handleBlEvents;
    private processPayment;
    renderMenuTrigger(): any;
    render(): any;
}
