import { EventEmitter } from '../../../stencil-public-runtime';
import { ICountry } from "../../../models/common";
export declare class IrPhoneInput {
    error: boolean;
    mobile_number: string;
    country_code: number;
    isVisible: boolean;
    currentHighlightedIndex: number;
    selectedItem: ICountry;
    filteredCountries: ICountry[];
    inputValue: string;
    el: HTMLElement;
    private popoverInstance;
    private triggerElement;
    private contentElement;
    private debounceTimeout;
    private commonService;
    textChange: EventEmitter<{
        phone_prefix: string;
        mobile: string;
    }>;
    phoneInputBlur: EventEmitter<FocusEvent>;
    phoneInputFocus: EventEmitter<FocusEvent>;
    private user_country;
    searchInput: HTMLInputElement;
    phoneInput: HTMLInputElement;
    componentWillLoad(): Promise<void>;
    componentDidLoad(): void;
    initializeCountries(): Promise<void>;
    handleCountryCodeChange(newValue: number, oldValue: number): void;
    handleMobileNumberChange(newValue: string, oldValue: string): void;
    selectCountryByProperty(property: any, value: any): void;
    setUpUserDefaultCountry(): Promise<void>;
    initializePopover(): void;
    handleOutsideClick: (event: MouseEvent) => void;
    handleKeyboardPress: (e: KeyboardEvent) => void;
    toggleVisibility(): Promise<void>;
    disconnectedCallback(): void;
    synchroniseSuggestionsBox(): void;
    handleAutoCompleteKeyDown(e: KeyboardEvent): void;
    selectItem(index: number): void;
    filterData(str: string): ICountry[];
    handleFilterInputChange(e: InputEvent): void;
    handleInputChange(e: InputEvent): void;
    render(): any;
}
