import { EventEmitter } from '../../../stencil-public-runtime';
export declare class IrInput {
    el: HTMLIrInputElement;
    inputId: string;
    leftIcon: boolean;
    inputStyles: Partial<CSSStyleDeclaration>;
    value: string;
    type: 'button' | 'checkbox' | 'color' | 'date' | 'datetime-local' | 'email' | 'file' | 'hidden' | 'image' | 'month' | 'number' | 'password' | 'radio' | 'range' | 'reset' | 'search' | 'submit' | 'tel' | 'text' | 'time' | 'url' | 'week';
    name: string;
    placeholder: string;
    inputid: string;
    class: string;
    required: boolean;
    disabled: boolean;
    readonly: boolean;
    maxlength: number;
    min: string | number;
    max: string | number;
    step: string | number;
    pattern: string;
    autocomplete: string;
    autofocus: boolean;
    size: number;
    multiple: boolean;
    label: string;
    error: boolean;
    mask: Record<string, unknown>;
    labelBackground: string;
    textChanged: EventEmitter<string>;
    inputFocus: EventEmitter<FocusEvent>;
    inputBlur: EventEmitter<FocusEvent>;
    private inputEl;
    private maskInstance;
    applyStyles(style: Partial<CSSStyleDeclaration>): void;
    private initializeOrUpdateMask;
    componentDidLoad(): void;
    maskPropChanged(newValue: Record<string, unknown>, oldValue: Record<string, unknown>): void;
    valueChanged(newValue: string, oldValue: string): void;
    handleBlur(event: FocusEvent): void;
    disconnectedCallback(): void;
    render(): any;
}
