export const booking = {
    agent: null,
    allowed_actions: [
        {
            code: '001',
            description: 'Pending',
        },
        {
            code: '003',
            description: 'Cancel',
        },
        {
            code: 'CANC_RA',
            description: 'Cancel & reopen',
        },
        {
            code: '004',
            description: 'No show',
        },
        {
            code: 'NOSHOW_RA',
            description: 'No show & reopen',
        },
    ],
    arrival: {
        code: '001',
        description: 'Not sure yet',
    },
    booked_on: {
        date: '2024-05-01',
        hour: 19,
        minute: 25,
    },
    booking_nbr: '53247983',
    channel_booking_nbr: null,
    cost: 0.0,
    currency: {
        code: 'USD',
        id: 4,
        symbol: null,
    },
    financial: {
        due_amount: 8114.1,
        due_dates: [
            {
                amount: 849.15,
                currencysymbol: 'US$',
                date: '2024-04-12',
                description: 'Cancellation',
                room: 'Premium Suites - test3 ',
            },
            {
                amount: 8114.1,
                currencysymbol: 'US$',
                date: '2024-04-13',
                description: 'Cancellation',
                room: 'Premium Suites - test3 ',
            },
            {
                amount: 849.15,
                currencysymbol: 'US$',
                date: '2024-05-01',
                description: 'Prepayment',
                room: 'Premium Suites - test3 ',
            },
        ],
        gross_cost: 0.0,
        gross_total: 8114.1,
        payments: null,
        total_amount: 7310.0,
    },
    format: {
        from_date: 'Sat, 27 Apr 2024',
        to_date: 'Sat, 11 May 2024',
    },
    from_date: '2024-04-27',
    guest: {
        address: '',
        cci: null,
        city: null,
        country_id: 2,
        dob: null,
        email: 'test@gmail.com',
        first_name: 'test',
        id: 195932,
        last_name: 'test',
        mobile: '+96112345678',
        subscribe_to_news_letter: false,
    },
    is_direct: true,
    is_editable: true,
    is_in_loyalty_mode: null,
    is_pms_enabled: true,
    occupancy: {
        adult_nbr: 2,
        children_nbr: 0,
        infant_nbr: null,
    },
    origin: {
        Icon: 'https://x.igloorooms.com/assets/images/png/direct.png',
        Label: 'Direct | Phone/Email',
    },
    ota_notes: null,
    pickup_info: null,
    promo_key: '',
    property: {
        address: null,
        adult_child_constraints: null,
        affiliates: null,
        agents: null,
        allowed_booking_sources: null,
        allowed_cards: null,
        allowed_payment_methods: null,
        amenities: null,
        area: null,
        baby_cot_offering: null,
        calendar_legends: null,
        city: null,
        contacts: null,
        country: null,
        currency: null,
        description: null,
        id: 42,
        images: null,
        internet_offering: null,
        is_frontdesk_enabled: null,
        is_pms_enabled: null,
        is_vacation_rental: null,
        location: null,
        max_nights: 0,
        name: 'igloorooms Demo Hotel',
        parking_offering: null,
        payment_methods: null,
        pets_acceptance: null,
        phone: null,
        pickup_service: null,
        postal: null,
        privacy_policy: null,
        promotions: null,
        roomtypes: null,
        social_media: null,
        space_theme: null,
        tax_statement: null,
        taxes: null,
        time_constraints: null,
    },
    remark: '',
    rooms: [
        {
            assigned_units_pool: 'ef13e5c6-aea6-4db7-b158-01bdc34f893f',
            bed_preference: '',
            cost: 0.0,
            days: [
                {
                    amount: 765.0,
                    cost: 0.0,
                    date: '2024-04-27',
                },
                {
                    amount: 765.0,
                    cost: 0.0,
                    date: '2024-04-28',
                },
                {
                    amount: 765.0,
                    cost: 0.0,
                    date: '2024-04-29',
                },
                {
                    amount: 765.0,
                    cost: 0.0,
                    date: '2024-04-30',
                },
                {
                    amount: 765.0,
                    cost: 0.0,
                    date: '2024-05-01',
                },
                {
                    amount: 765.0,
                    cost: 0.0,
                    date: '2024-05-02',
                },
                {
                    amount: 765.0,
                    cost: 0.0,
                    date: '2024-05-03',
                },
                {
                    amount: 765.0,
                    cost: 0.0,
                    date: '2024-05-04',
                },
                {
                    amount: 765.0,
                    cost: 0.0,
                    date: '2024-05-05',
                },
                {
                    amount: 85.0,
                    cost: 0.0,
                    date: '2024-05-06',
                },
                {
                    amount: 85.0,
                    cost: 0.0,
                    date: '2024-05-07',
                },
                {
                    amount: 85.0,
                    cost: 0.0,
                    date: '2024-05-08',
                },
                {
                    amount: 85.0,
                    cost: 0.0,
                    date: '2024-05-09',
                },
                {
                    amount: 85.0,
                    cost: 0.0,
                    date: '2024-05-10',
                },
            ],
            from_date: '2024-04-27',
            gross_cost: 0.0,
            gross_total: 8114.1,
            guest: {
                address: null,
                cci: null,
                city: null,
                country_id: null,
                dob: null,
                email: null,
                first_name: 'test3',
                id: null,
                last_name: null,
                mobile: null,
                subscribe_to_news_letter: null,
            },
            identifier: 'b6998d8b-f0f6-4693-bc0a-12089a674763',
            notes: null,
            occupancy: {
                adult_nbr: 2,
                children_nbr: 0,
                infant_nbr: null,
            },
            ota_taxes: null,
            rateplan: {
                assignable_units: null,
                cancelation: '<u><b>Cancellation</b></u>: 100% of the total price will be charged if cancelled after Saturday, 13 Apr 2024, 22:00 or in case of no show.\r\n',
                custom_text: null,
                guarantee: '<u><b>Guarantee</b></u>: First night from your booking will be charged.',
                id: 3755,
                is_active: null,
                is_booking_engine_enabled: null,
                is_channel_enabled: null,
                is_closed: null,
                is_non_refundable: false,
                is_targeting_travel_agency: null,
                name: 'Half-board',
                rate_restrictions: null,
                selected_variation: {
                    adult_child_offering: '2 adults',
                    adult_nbr: 2,
                    amount: null,
                    amount_per_night: null,
                    child_nbr: 0,
                    discount_pct: null,
                    is_lmd: null,
                    nights_nbr: null,
                    total_before_discount: null,
                },
                sell_mode: null,
                short_name: null,
                variations: null,
            },
            roomtype: {
                amenities: null,
                availabilities: null,
                bedding_setup: null,
                description: null,
                exposed_inventory: null,
                id: 111,
                images: null,
                inventory: null,
                is_active: null,
                is_bed_configuration_enabled: null,
                main_image: null,
                name: 'Premium Suites',
                occupancy_default: null,
                occupancy_max: null,
                physicalrooms: null,
                pre_payment_amount: null,
                rate: null,
                rateplans: null,
                size: null,
                smoking_option: null,
            },
            smoking_option: null,
            to_date: '2024-05-11',
            total: 7310.0,
            unit: {
                calendar_cell: null,
                housekeeper: null,
                id: 3,
                name: '102',
            },
        },
    ],
    source: {
        code: '003',
        description: 'Phone/Email',
        id: null,
        tag: '',
        type: null,
    },
    status: {
        code: '002',
        description: 'Confirmed',
    },
    system_id: 14266943,
    to_date: '2024-05-11',
    total: 7310.0,
};
//# sourceMappingURL=dummy-data.js.map
