import { Booking } from "../../models/booking.dto";
import { AllowedPaymentMethod } from "../../models/property";
export declare class IrInvoice {
    email: string;
    propertyId: number;
    baseUrl: string;
    language: string;
    bookingNbr: string;
    status: 0 | 1;
    perma_link: string;
    aName: string;
    headerShown: boolean;
    footerShown: boolean;
    headerMessageShown: boolean;
    locationShown: boolean;
    be: boolean;
    ticket: string;
    version: string;
    booking: Booking;
    isAuthenticated: boolean;
    isLoading: boolean;
    cancellation_message: string;
    guarantee_message: string;
    private token;
    private propertyService;
    private commonService;
    private authService;
    private paymentService;
    private bookingListingAppService;
    private payment_option;
    private amount;
    private bookingCancellation;
    private privacyPolicyRef;
    componentWillLoad(): Promise<void>;
    handleBookingNumberChange(newValue: any, oldValue: any): Promise<void>;
    handleTicketChange(newValue: any, oldValue: any): Promise<void>;
    private fetchBooking;
    fetchData(language?: string, resetLanguage?: boolean): Promise<void>;
    openPrivacyPolicy(e: CustomEvent): Promise<void>;
    handleLanguageChanged(e: CustomEvent): Promise<void>;
    setAmountAndCancelationPolicy(): Promise<void>;
    renderBookingDetailHeader(): string;
    getPropertyEmail(): string;
    renderPaymentText(paymentOption: AllowedPaymentMethod): any;
    private processPayment;
    render(): any;
    private formatOccupancy;
}
