import { Booking } from "../../models/booking.dto";
import { AllowedPaymentMethod } from "../../models/property";
export declare class IrInvoice {
    email: string;
    propertyId: number;
    baseUrl: string;
    language: string;
    bookingNbr: string;
    status: 0 | 1;
    perma_link: string;
    aName: string;
    headerShown: boolean;
    footerShown: boolean;
    booking: Booking;
    token: string;
    private propertyService;
    private commonService;
    private authService;
    private paymentService;
    alertDialog: HTMLIrAlertDialogElement;
    componentWillLoad(): Promise<void>;
    private detectPaymentOrigin;
    handleBookingNumberChange(newValue: any, oldValue: any): Promise<void>;
    init(): Promise<void>;
    fetchData(): Promise<void>;
    renderBookingDetailHeader(): string;
    getPropertyEmail(): string;
    renderPaymentText(paymentOption: AllowedPaymentMethod): any;
    render(): any;
}
